### ISSUE TITLE
Ingredient Lookup

### ISSUE THREAD

**Issue by nikstaaar** [nikstaaar/capstone-project#1]
as a user 
I want to Lookup Ingredients, 
so that I can see which ingredients I can add.

## ac

- [ ] there is in input field at the top of the page
- [ ] a list of available items pops up when I type in the input field

![Image](https://user-images.githubusercontent.com/104061897/190644166-e4534be6-c836-4729-ad00-601bbed1589e.png)

## tasks
- [ ] create a "my bar" page
- [ ] fetch data from cocktail db
- [ ] create input
- [ ] create pop-up list
