### ISSUE TITLE
Cocktail Finder

### ISSUE THREAD

**Issue by nikstaaar** [nikstaaar/capstone-project#10]
As a User
I want to see which Cocktails are possible with my saved Ingredients
so that I can discover new Cocktails I can make

<img width="425" alt="Screenshot 2022-09-29 at 11 25 59" src="https://user-images.githubusercontent.com/104061897/192995145-a31855a3-7483-48fb-aa43-7fbbf11bf69a.png">

## AC

- [ ] Possible Cocktails are shown on the Cocktails Page
- [ ] Cocktails are shown with Name, Ingredients etc.

## Tasks 
- [ ]  Build Api for cocktails
- [ ]  Write function to compare ingredients to cocktails
- [ ]  Build Cocktail Page
- [ ]  Style Cocktail Page

**Comment by mbosselmann** [comment]
Hi Niklas,
I like your user story, but I would prefer to see a wireframe of the Cocktail Page for better understanding. :)

**Comment by nikstaaar** [comment]
Thank you for your feedback Mareike, 
i have added a quick wireframe. I hope this helps to get a more clear understanding of the user story.

**Comment by mbosselmann** [comment]
Yes, thank you! Happy hacking! 💪
