### ISSUE TITLE
Add Ingredient

### ISSUE THREAD

**Issue by nikstaaar** [nikstaaar/capstone-project#2]
as a user
I want to add Ingredients to my bar,
so that I can have an overview over my ingredients.

##  ac

- [ ] there is an "add "button if the ingredient isn't already saved 
- [ ] otherwise the button says "saved"
- [ ] the saved ingredients are listed.

![Image](https://user-images.githubusercontent.com/104061897/190644006-df37e4c3-3d92-4d11-9fbc-cc67a4bd6545.png)

## tasks

- [ ] add button to search items
- [ ] create use store for saved items
- [ ] render out saved items
