### ISSUE TITLE
Delete Ingredient

### ISSUE THREAD

**Issue by nikstaaar** [nikstaaar/capstone-project#3]
as a user
I want to remove Ingredients from my bar,
so that I can keep my bar organised.

##  ac

- [ ] there is an "remove" button on each saved ingredient
- [ ] pressing the button removes the ingredient from my bar

![Image](https://user-images.githubusercontent.com/104061897/190658740-b61da621-bff9-42ea-a5e2-08f4ee26f97e.png)

## tasks

- [ ] add remove button to saved items
- [ ] create onClick function to remove items from useStore

**Comment by OmerAdam34** [comment]
quick and clear! thumbs up.
