### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by nikstaaar** [nikstaaar/capstone-project#8]
As a user
I want the app to be styled
so that I can intuitively understand how the app works 

![Image](https://user-images.githubusercontent.com/104061897/192232046-8ec61a6b-b0c5-4181-a88d-5aaeab27b763.png)

## AC
- [ ] all components have distinct styles
- [ ] ingredients are shown on different coloured cards
- [ ] cards become opaque when ingredients are saved

## Tasks

- [ ] learn styled components
- [ ] create a grid layout
- [ ] implement design from my figma prototype
